apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: chartmuseum-secrets
spec:
  target:
    name: chartmuseum-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    - remoteRef:
        key: chartmuseum
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        key: chartmuseum
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
    - remoteRef:
        key: chartmuseum
        property: BASIC_AUTH_USER
      secretKey: BASIC_AUTH_USER
    - remoteRef:
        key: chartmuseum
        property: BASIC_AUTH_PASS
      secretKey: BASIC_AUTH_PASS
