apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  target:
    name: gitlab-runner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    - remoteRef:
        key: gitlab-runner
        property: RUNNER_TOKEN
      secretKey: runner-token
    - remoteRef:
        key: gitlab-runner
        property: RUNNER_REGISTRATION_TOKEN
      secretKey: runner-registration-token
