FROM debian:latest

# Installing dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  coreutils \
  curl \
  file \
  git \
  && rm -rf /var/lib/apt/lists/*

CMD [ "/bin/bash" ]
