version: '3'

tasks:
  unit-test:
    - go test -v ./...
  unit-test-with-report:
    - go test -v ./... -coverpkg=./... -coverprofile cover.out
    - go tool cover -html cover.out -o coverage.html
  integration-test-init:
    - go run . clean
