version: '3'

tasks:
  unit-test:
    - go test -v -short ./...
  unit-test-with-report:
    - go test -v ./... -coverpkg=./... -coverprofile cover.out
    - go tool cover -html cover.out -o coverage.html
  integration-tests:
#    - go run . init --help # todo: add params
    - go test -v -run TestAreS3BucketsLiveIntegration ./internal/aws
#    - go run . create
    - go test -v -run TestArgoCDLivenessIntegration ./internal/argocd
    - go test -v -run TestArgoWorkflowLivenessIntegration ./internal/argocd
    - go test -v -run TestGitLabLivenessIntegration ./internal/gitlab
    - go test -v -run TestMetaphorsLivenessIntegration ./internal/metaphor
#    - go run . destroy
    - go test -v -run TestIsVPCByTagDestroyedIntegration ./internal/aws
    - go test -v -run TestIsLoadBalancerByTagDestroyedIntegration ./internal/aws
    - go test -v -run TestAreS3BucketsDestroyedIntegration ./internal/aws
    - go test -v -run TestIsKMSKeyAliasDestroyedIntegration ./internal/aws
    - go test -v -run TestIsEKSDestroyedIntegration ./internal/aws
    - go test -v -run TestAreEC2VolumesDestroyedIntegration ./internal/aws
