apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://external-secrets.github.io/kubernetes-external-secrets'
    targetRevision: 8.5.0
    helm:
      values: |-
        env:
          AWS_REGION: <AWS_DEFAULT_REGION>
          AWS_DEFAULT_REGION: <AWS_DEFAULT_REGION>
          VAULT_ADDR: https://vault.<AWS_HOSTED_ZONE_NAME>
        serviceAccount:
          name: external-secrets
    chart: kubernetes-external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true