apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: appDir
      value: /src/{{workflow.parameters.appName}}
    - name: appName
      value: "{{workflow.parameters.appName}}"
    - name: chartDir
      value: charts/{{workflow.parameters.appName}}
    - name: ciCommitSha
      value: "{{workflow.parameters.ciCommitSha}}"
    - name: branch
      value: "{{workflow.parameters.branch}}"
    - name: gitRepoURL
      value: "{{workflow.parameters.gitRepoURL}}"
    - name: shortSha
      value: "{{workflow.parameters.shortSha}}"
  templates:
  - name: main
    steps:
    - - name: checkout
        templateRef:
          name: cwft-git
          template: git-checkout-with-gitops
          clusterScope: true
        arguments:
          parameters:
          - name: appDir
            value: "{{workflow.parameters.appDir}}"
          - name: branch
            value: "{{workflow.parameters.branch}}"
          - name: gitRepoURL
            value: "{{workflow.parameters.gitRepoURL}}"

    - - name: publish-container
        templateRef:
          name: cwft-docker
          template: docker-build
          clusterScope: true
        arguments:
          artifacts:
          - name: repo-source
            from: "{{steps.checkout.outputs.artifacts.repo-source}}"
          parameters:
          - name: appDir
            value: "{{workflow.parameters.appDir}}"
          - name: appName
            value: "{{workflow.parameters.appName}}"
          - name: ciCommitSha
            value: "{{workflow.parameters.ciCommitSha}}"

    - - name: get-initial-chart-version
        templateRef:
          name: cwft-helm
          template: helm-get-chart-version
          clusterScope: true
        arguments:
          artifacts:
          - name: repo-source
            from: "{{steps.checkout.outputs.artifacts.repo-source}}"
          parameters:
          - name: appDir
            value: "{{workflow.parameters.appDir}}"
          - name: chartDir
            value: "{{workflow.parameters.chartDir}}"

    - - name: set-chart-versions
        templateRef:
          name: cwft-helm
          template: helm-set-chart-versions
          clusterScope: true
        arguments:
          artifacts:
            - name: repo-source
              from: "{{steps.checkout.outputs.artifacts.repo-source}}"
          parameters:
          - name: appDir
            value: "{{workflow.parameters.appDir}}"
          - name: chartDir
            value: "{{workflow.parameters.chartDir}}"
          - name: chartVersion
            value: "{{steps.get-initial-chart-version.outputs.result}}-rc+{{workflow.parameters.shortSha}}"
          - name: ciCommitSha
            value: "{{workflow.parameters.ciCommitSha}}"

    - - name: publish-helm-chart
        templateRef:
          name: cwft-helm
          template: helm-publish-chart
          clusterScope: true
        arguments:
          artifacts:
          - name: repo-source
            from: "{{steps.set-chart-versions.outputs.artifacts.repo-source}}"
          parameters:
          - name: appDir
            value: "{{workflow.parameters.appDir}}"
          - name: chartDir
            value: "{{workflow.parameters.chartDir}}"
