/*
 * Swagger API for Kubefirst - OpenAPI 3.0
 *
 * Sample API for Kubefirst UI - Local
 *
 * API version: 0.0.1
 * Contact: kray@kubefrist.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"log"
	"net/http"

	"github.com/spf13/viper"
)

func ConfigsGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	w.WriteHeader(http.StatusOK)

	configValues := []Config{
		{
			Key:   "ADMIN_EMAIL",
			Value: viper.GetString("adminemail"),
		},
		{
			Key:   "CLUSTER_NAME",
			Value: viper.GetString("cluster-name"),
		},
		{
			Key:   "GITHUB_HOST",
			Value: viper.GetString("github.host"),
		},
		{
			Key:   "GITHUB_OWNER",
			Value: viper.GetString("github.owner"),
		},
		{
			Key:   "HOSTED_ZONE_NAME",
			Value: viper.GetString("aws.hostedzonename"),
		},
	}

	jsonData, err := json.Marshal(configValues)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		log.Println(err)
		return
	}

	_, err = w.Write(jsonData)

	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		log.Println(err)
		return
	}
}
