/*
 * Swagger API for Kubefirst - OpenAPI 3.0
 *
 * Sample API for Kubefirst UI - Local
 *
 * API version: 0.0.1
 * Contact: kray@kubefrist.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Config struct {

	Key string `json:"key"`

	Value string `json:"value"`
}
