apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs
spec:
  replicas: 2
  selector:
    matchLabels:
      run: mkdocs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mkdocs
    spec:
      containers:
        - image: @ECR_REGISTRY@/mkdocs:@DOCKER_TAG@
          name: mkdocs
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: "256Mi"
            requests:
              cpu: 40m
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 30
      restartPolicy: Always
