kind: Service
apiVersion: v1
metadata:
  name: mkdocs
  labels:
    run: mkdocs
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  selector:
    run: mkdocs
  externalTrafficPolicy: Cluster
  type: NodePort
