apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: ci-secrets
spec:
  target:
    name: ci-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    # username used for accessing git - this is the name of the personal access token, default is kubefirst
    - remoteRef:
        key: ci-secrets
        property: USERNAME
      secretKey: USERNAME
    # personal access token associated with username above
    - remoteRef:
        key: ci-secrets
        property: PERSONAL_ACCESS_TOKEN
      secretKey: PERSONAL_ACCESS_TOKEN
    # access key id to connect to aws
    - remoteRef:
        key: ci-secrets
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    # access key to connect to aws
    - remoteRef:
        key: ci-secrets
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
    # chartmuseum admin username
    - remoteRef:
        key: ci-secrets
        property: BASIC_AUTH_USER
      secretKey: BASIC_AUTH_USER
    # chartmuseum admin password
    - remoteRef:
        key: ci-secrets
        property: BASIC_AUTH_PASS
      secretKey: BASIC_AUTH_PASS
---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: argo-secrets
spec:
  target:
    name: argo-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    # client-id used for oidc auth with keycloak
    - remoteRef:
        key: admin/oidc/argo
        property: application_id
      secretKey: client-id
    # client-id used for oidc auth with keycloak
    - remoteRef:
        key: admin/oidc/argo
        property: secret
      secretKey: client-secret
