apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: ci-secrets
spec:
  backendType: vault
  vaultMountPoint: kubernetes/kubefirst
  vaultRole: external-secrets
  kvVersion: 2
  data:
    # username used for accessing git - this is the name of the personal access token, default is kubefirst
    - name: USERNAME
      key: secret/data/ci-secrets
      property: USERNAME
    # personal access token associated with username above
    - name: PERSONAL_ACCESS_TOKEN
      key: secret/data/ci-secrets
      property: PERSONAL_ACCESS_TOKEN
    # access key id to connect to aws
    - name: AWS_ACCESS_KEY_ID
      key: secret/data/ci-secrets
      property: AWS_ACCESS_KEY_ID
    # access key to connect to aws
    - name: AWS_SECRET_ACCESS_KEY
      key: secret/data/ci-secrets
      property: AWS_SECRET_ACCESS_KEY
    # chartmuseum admin username
    - name: BASIC_AUTH_USER
      key: secret/data/ci-secrets
      property: BASIC_AUTH_USER
    # chartmuseum admin password
    - name: BASIC_AUTH_PASS
      key: secret/data/ci-secrets
      property: BASIC_AUTH_PASS
---
  apiVersion: "kubernetes-client.io/v1"
  kind: ExternalSecret
  metadata:
    name: argo-secrets
  spec:
    backendType: vault
    vaultMountPoint: kubernetes/kubefirst
    vaultRole: external-secrets
    kvVersion: 2
    data:
      # client-id used for oidc auth with keycloak
      - name: client-id
        key: secret/data/admin/oidc/argo
        property: application_id
      # client-id used for oidc auth with keycloak
      - name: client-secret
        key: secret/data/admin/oidc/argo
        property: secret