apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaphor-production
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://gitlab.<AWS_HOSTED_ZONE_NAME>/kubefirst/gitops
    path: components/production/metaphor
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
