package civo

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/kubefirst/kubefirst/pkg"
	"github.com/rs/zerolog/log"
)

func DownloadTools(helmClientPath, helmClientVersion, kubectlClientPath, kubectlClientVersion, localOs, localArchitecture, terraformClientVersion, toolsDirPath string) error {

	log.Info().Msg("starting downloads...")

	// create folder if it doesn't exist
	err := createDirIfDontExist(toolsDirPath)
	if err != nil {
		return err
	}

	errorChannel := make(chan error)
	wgDone := make(chan bool)
	// create a waiting group (translating: create a queue of functions, and only pass the wg.Wait() function down
	// bellow after all the wg.Add(3) functions are done (wg.Done)
	var wg sync.WaitGroup
	wg.Add(3)

	go func() {

		kubectlDownloadURL := fmt.Sprintf(
			"https://dl.k8s.io/release/%s/bin/%s/%s/kubectl",
			kubectlClientVersion,
			localOs,
			localArchitecture,
		)
		log.Info().Msgf("Downloading kubectl from: %s", kubectlDownloadURL)
		err = DownloadFile(kubectlClientPath, kubectlDownloadURL)
		if err != nil {
			errorChannel <- err
			return
		}

		err = os.Chmod(kubectlClientPath, 0755)
		if err != nil {
			errorChannel <- err
			return
		}

		log.Info().Msgf("going to print the kubeconfig env in runtime: %s", os.Getenv("KUBECONFIG"))

		kubectlStdOut, kubectlStdErr, err := pkg.ExecShellReturnStrings(kubectlClientPath, "version", "--client", "--short")
		log.Info().Msgf("-> kubectl version:\n\t%s\n\t%s\n", kubectlStdOut, kubectlStdErr)
		if err != nil {
			errorChannel <- fmt.Errorf("failed to call kubectlVersionCmd.Run(): %v", err)
			return
		}
		wg.Done()
		log.Info().Msg("Kubectl download finished")
	}()

	go func() {

		terraformDownloadURL := fmt.Sprintf(
			"https://releases.hashicorp.com/terraform/%s/terraform_%s_%s_%s.zip",
			terraformClientVersion,
			terraformClientVersion,
			localOs,
			localArchitecture,
		)
		log.Info().Msgf("Downloading terraform from %s", terraformDownloadURL)
		terraformDownloadZipPath := fmt.Sprintf("%s/terraform.zip", toolsDirPath)
		err = DownloadFile(terraformDownloadZipPath, terraformDownloadURL)
		if err != nil {
			errorChannel <- fmt.Errorf("error downloading terraform file, %v", err)
			return
		}

		unzip(terraformDownloadZipPath, toolsDirPath)

		err = os.Chmod(toolsDirPath, 0777)
		if err != nil {
			errorChannel <- err
			return
		}

		err = os.Chmod(fmt.Sprintf("%s/terraform", toolsDirPath), 0755)
		if err != nil {
			errorChannel <- err
			return
		}
		err = os.RemoveAll(fmt.Sprintf("%s/terraform.zip", toolsDirPath))
		if err != nil {
			errorChannel <- err
			return
		}
		// todo output terraform client version to be consistent with others
		wg.Done()
		log.Info().Msg("Terraform download finished")
	}()

	go func() {
		helmDownloadURL := fmt.Sprintf(
			"https://get.helm.sh/helm-%s-%s-%s.tar.gz",
			helmClientVersion,
			localOs,
			localArchitecture,
		)
		log.Info().Msgf("Downloading helm from %s", helmDownloadURL)
		helmDownloadTarGzPath := fmt.Sprintf("%s/helm.tar.gz", toolsDirPath)

		err = DownloadFile(helmDownloadTarGzPath, helmDownloadURL)
		if err != nil {
			errorChannel <- err
			return
		}

		helmTarDownload, err := os.Open(helmDownloadTarGzPath)
		if err != nil {
			errorChannel <- fmt.Errorf("could not read helm download content")
			return
		}

		extractFileFromTarGz(
			helmTarDownload,
			fmt.Sprintf("%s-%s/helm", localOs, localArchitecture),
			helmClientPath,
		)
		err = os.Chmod(helmClientPath, 0755)
		if err != nil {
			errorChannel <- err
			return
		}

		// currently argocd init values is generated by kubefirst ssh
		// todo helm install argocd --create-namespace --wait --values ~/.kubefirst/argocd-init-values.yaml argo/argo-cd
		helmStdOut, helmStdErr, err := pkg.ExecShellReturnStrings(
			helmClientPath,
			"version",
			"--client",
			"--short",
		)
		if err != nil {
			log.Info().Msg(helmStdErr)
			errorChannel <- fmt.Errorf("error executing helm version command: %v", err)
			return
		}
		os.Remove(helmDownloadTarGzPath)

		log.Info().Msgf("Helm version: %s", helmStdOut)

		wg.Done()

		log.Info().Msg("Helm download finished")

	}()

	go func() {
		wg.Wait()
		close(wgDone)
	}()

	select {
	case <-wgDone:
		log.Info().Msg("downloads finished")
		return nil
	case err = <-errorChannel:
		close(errorChannel)
		return err
	}
}

// DownloadFile Downloads a file from the "url" parameter, localFilename is the file destination in the local machine.
func DownloadFile(localFilename string, url string) error {
	// create local file
	out, err := os.Create(localFilename)
	if err != nil {
		return err
	}
	defer out.Close()

	// get data
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	// check server response
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("unable to download the required file, the HTTP return status is: %s", resp.Status)
	}

	// writer the body to the file
	_, err = io.Copy(out, resp.Body)
	if err != nil {
		return err
	}

	return nil
}

func extractFileFromTarGz(gzipStream io.Reader, tarAddress string, targetFilePath string) {
	uncompressedStream, err := gzip.NewReader(gzipStream)
	if err != nil {
		log.Panic().Msg("extractTarGz: NewReader failed")
	}

	tarReader := tar.NewReader(uncompressedStream)

	for {
		header, err := tarReader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Panic().Msgf("extractTarGz: Next() failed: %s", err.Error())
		}
		log.Info().Msg(header.Name)
		if header.Name == tarAddress {
			switch header.Typeflag {
			case tar.TypeReg:
				outFile, err := os.Create(targetFilePath)
				if err != nil {
					log.Panic().Msgf("extractTarGz: Create() failed: %s", err.Error())
				}
				if _, err := io.Copy(outFile, tarReader); err != nil {
					log.Panic().Msgf("extractTarGz: Copy() failed: %s", err.Error())
				}
				outFile.Close()

			default:
				log.Info().Msgf(
					"extractTarGz: uknown type: %s in %s\n",
					string(header.Typeflag),
					header.Name)
			}

		}
	}
}

func unzip(zipFilepath string, unzipDirectory string) error {
	dst := unzipDirectory
	archive, err := zip.OpenReader(zipFilepath)
	if err != nil {
		return err
	}
	defer archive.Close()

	for _, f := range archive.File {
		filePath := filepath.Join(dst, f.Name)
		log.Info().Msgf("unzipping file %s", filePath)

		if !strings.HasPrefix(filePath, filepath.Clean(dst)+string(os.PathSeparator)) {
			return errors.New("invalid file path")
		}
		if f.FileInfo().IsDir() {
			log.Info().Msg("creating directory...")
			err = os.MkdirAll(filePath, os.ModePerm)
			if err != nil {
				return err
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(filePath), os.ModePerm); err != nil {
			return err
		}

		dstFile, err := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
		if err != nil {
			return err
		}

		fileInArchive, err := f.Open()
		if err != nil {
			return err
		}

		if _, err := io.Copy(dstFile, fileInArchive); err != nil {
			return err
		}

		dstFile.Close()
		fileInArchive.Close()
	}
	return nil
}

func createDirIfDontExist(toolsDirPath string) error {
	if _, err := os.Stat(toolsDirPath); errors.Is(err, fs.ErrNotExist) {
		err = os.Mkdir(toolsDirPath, 0777)
		if err != nil {
			return err
		}
	}
	return nil
}
