apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .DeploymentName }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: "registry/environments/{{ .Environment }}/{{ .AppName }}"
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: "{{ .Namespace }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
