name: Check Commit Messages
on: push

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      
      - name: Lint the commits
        uses: wagoid/commitlint-github-action@v5.4.3
        with:
          configFile: .commitlintrc.js
          failOnWarnings: true
