name: golangci-lint
on:
  push:
  
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    strategy:
      matrix:
        go: [1.18]
        os: [macos-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
      #     version: v1.50.0
      #     args: --timeout 10m
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.18"
        
