name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:
env:
  RELEASE_DOCS_BRANCH_REF: 'refs/heads/main'

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install mkdocs-material
    - run: rm -rf ./dist
    - run: mkdocs build --no-directory-urls -d dist
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: ./dist

  deploy-preprod:
    name: Deploy Preprod
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      if: ${{ github.ref }} == ${{ env.RELEASE_DOCS_BRANCH_REF }}
      with:
        name: dist
        path: ./dist
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist'
        DEST_DIR: 'preprod'

  invalidate-cloudfront:
    name: Invalidate CloudFront
    needs: [build, deploy-preprod]
    runs-on: ubuntu-latest
    steps:
    - uses: chetan/invalidate-cloudfront-action@v2
      if: ${{ github.ref }} == ${{ env.RELEASE_DOCS_BRANCH_REF }}
      env:
        PATHS: '/preprod/*'
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
