name: Test CI

on:
  push:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Running Tests
      run: |
        docker-compose -f docker-compose-test.yaml build --no-cache \
        && docker compose -f docker-compose-test.yaml run kubefirst-unit-tests
